### ISSUE TITLE
Searchlog Analyse

### ISSUE THREAD

**Issue by Kringels90** [sixeco/ProjectAlbatross#17]
Als Usability - Fachmann möchte ich analysieren, welche Suchanfragen die Nutzer meiner Suchmaschine am meisten eingeben, um diese meistgesuchten Tehmen besser zu zeigen.

**Comment by haribomona** [comment]
Wordclouds und Tabellen zur Erfassung der Top 10 in den Kws erledigt.
Next Step: Zusammenschreiben

**Comment by haribomona** [comment]
[elastic search.docx](https://github.com/sixeco/ProjectAlbatross/files/357549/elastic.search.docx)
