### ISSUE TITLE
Informationsbedürfnisse identifizieren 

### ISSUE THREAD

**Issue by Kringels90** [sixeco/ProjectAlbatross#18]
Als Usability - Fachmann möchte ich das Informationsbedüfniss meines Nutzers kennen, um die Suchmaschine seinen Anforderungen anzupassen.

**Comment by regina272** [comment]
[Informationsbedürfnisse.pdf](https://github.com/sixeco/ProjectAlbatross/files/336605/Informationsbedurfnisse.pdf)
